---
- name: Create infra group
  group:
    name: infra
    state: present

- name: Add k8 Users
  user: name={{ item.username }}  group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }} generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
  with_items: "{{ k8_users }}"
  tags:
    - user

- name: Install git
  yum:
    name: git
    state: present

#deploy inventory script
- template:
    src: send_inv.sh.j2
    dest: /root/send_inv.sh
    mode: 0744
