---
- name: Create infra group
  group:
    name: infra
    state: present

- name: Add app Users
  user: name={{ item.username }}  group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }} generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
  with_items: "{{ app_users }}"
  tags:
    - user

- name: Install nginx
  apt:
    name: nginx
    state: present
