---
# deploy go
- template:
    src: profile.j2
    dest: /root/.profile
    mode: 0744
- file:
    path: /root/code
    state: directory

- name: get the go code
  shell: 'wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz'
  args:
    chdir: /root
- name: unpack the go code
  shell: 'tar -C /root -xzf go1.10.3.linux-amd64.tar.gz'
  args:
    chdir: /root
  register: unpack_go

- debug:
    var=unpack_go

- name: Create directory for the jsonnet templates
  file:
    path: /root/prometheus
    state: directory

- template:
    src: prometheus.jsonnet.j2
    dest: /root/prometheus/prometheus.jsonnet

- template:
    src: alertmanager-config.yml.j2
    dest: /root/prometheus/alertmanager-config.yml

- template:
    src: sc-pro1.yaml.j2
    dest: /root/prometheus/sc-pro1.yaml

- name: Create output directory for the manifests
  file:
    path: /root/prometheus/manifests
    state: directory

- name: remove the old jsonnet file
  file:
    path: /root/prometheus/jsonnetfile.json
    state: absent
